# Generated by Django 3.0.7 on 2020-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpe_infromation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu', models.CharField(max_length=10)),
                ('std', models.CharField(max_length=20)),
                ('count', models.CharField(max_length=1)),
            ],
        ),
    ]
