# Generated by Django 3.0.7 on 2020-06-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OderCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcpesend', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('idcpeto', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cpe_infromation',
        ),
        migrations.AddField(
            model_name='acceptcommand',
            name='idcpeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.OderCommand'),
        ),
    ]
