# Generated by Django 3.0.7 on 2020-06-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200614_1427'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcceptCommand',
        ),
    ]
