# Generated by Django 3.0.7 on 2020-06-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_delete_acceptcommand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odercommand',
            options={'ordering': ('date',), 'verbose_name': 'รายการที่', 'verbose_name_plural': 'รายการ'},
        ),
        migrations.AddField(
            model_name='odercommand',
            name='id_oder',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='odercommand',
            table='odercommand',
        ),
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.OderCommand')),
            ],
            options={
                'verbose_name': 'รายการที่',
                'verbose_name_plural': 'รายการ',
                'db_table': 'oderitem',
            },
        ),
    ]
