# Generated by Django 3.0.7 on 2020-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200614_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odercommand',
            name='id_oder',
        ),
    ]
