# Generated by Django 3.0.7 on 2020-06-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_odercommand_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odercommand',
            name='user',
        ),
    ]
