# Generated by Django 3.0.7 on 2020-06-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_odercommand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odercommand',
            name='idcpesend',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='odercommand',
            name='idcpeto',
            field=models.IntegerField(max_length=11),
        ),
    ]
