# Generated by Django 3.0.7 on 2020-06-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200616_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='count',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
