# Generated by Django 3.0.7 on 2021-05-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_userprofile_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odercommand',
            options={'ordering': ('-date',), 'verbose_name': 'รายการที่', 'verbose_name_plural': 'รายการ'},
        ),
    ]
