# Generated by Django 3.0.7 on 2021-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_bg_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
