# Generated by Django 3.0.7 on 2021-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20210611_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='displayname',
            field=models.CharField(default='noverify', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='count',
            field=models.BooleanField(default=False),
        ),
    ]
