# Generated by Django 3.0.7 on 2021-06-20 03:01

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_userprofile_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_field',
            field=cropperjs.models.CropperImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
