# Generated by Django 3.0.7 on 2021-06-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0022_remove_userprofile_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('id_someone', models.IntegerField(max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('idmy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Links: ',
                'verbose_name_plural': 'Like-ecosystem',
                'db_table': 'Like',
            },
        ),
    ]
