# Generated by Django 3.0.7 on 2021-06-23 03:01

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_auto_20210620_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bg_pic',
            field=cropperjs.models.CropperImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cropperjs.models.CropperImageField(upload_to=''),
        ),
    ]
