# Generated by Django 3.0.7 on 2021-06-23 03:16

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_auto_20210623_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bg_pic',
            field=cropperjs.models.CropperImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cropperjs.models.CropperImageField(upload_to='images'),
        ),
    ]
