# Generated by Django 3.0.7 on 2021-06-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_auto_20210623_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bg_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
