# Generated by Django 3.0.7 on 2021-06-23 04:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0031_auto_20210623_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bg_pic',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[800, 400], upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[500, 500], upload_to=''),
        ),
    ]
