# Generated by Django 3.0.7 on 2021-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_auto_20210623_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='indexpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='')),
                ('pic2', models.ImageField(upload_to='')),
                ('pic3', models.ImageField(upload_to='')),
            ],
        ),
    ]
