# Generated by Django 3.0.7 on 2021-06-27 10:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_auto_20210627_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_bg_pic',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='profileback.jpg', force_format=None, keep_meta=True, quality=100, size=[400, 500], upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='profile.jpg', force_format=None, keep_meta=True, quality=100, size=[700, 700], upload_to=''),
        ),
    ]
